# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nottitapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://gyarbij.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_746f1db47ac2496f9cda6ac9e6b85249 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f55f4d2f1d754464aec7fa59ccbb2f1f }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: gyarbij.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_746f1db47ac2496f9cda6ac9e6b85249 }}/nottit:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'nottitapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3f1bf70fb7e24dbe90615de8f45e12f2 }}
        images: 'gyarbij.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_746f1db47ac2496f9cda6ac9e6b85249 }}/nottit:${{ github.sha }}'